### ISSUE TITLE
BOM links not working

### ISSUE THREAD

**Issue by SwannSchilling** [liaochikon/ALTO-3D-Printed-6-Axis-Robotic-Arm#1]
Hey there although its been updated recently the links seem to not be valid anymore!
I am super interested in those harmonic drives, could you check those links please?
This would be super helpful!

**Comment by liaochikon** [comment]
The page to buy the stepper driver and harmonic drives were gone a few month ago.
I've managed to find another store for the harmonic drives, but still looking for alternatives for stepper driver.
Currently planning to make my own stepper driver board.

Here's link for harmonic drives:
https://world.taobao.com/item/702811518003.htm?spm=a21wu.10013406-tw.taglist-content.2.460340f1MlBiPW
Hope this would help~

**Comment by SwannSchilling** [comment]
Thank you so much!! This is great news!
They used to be so costly! I will order them right now!! :)

**Comment by SwannSchilling** [comment]
I will close it as resolved! :)
